// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetType.Persistense.Database;

#nullable disable

namespace PetType.Persistense.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220914163236_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PetCategory")
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PetType.Domain.PetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PetCategories", "PetCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = " PetCategory 0"
                        },
                        new
                        {
                            Id = 2,
                            Name = " PetCategory 1"
                        },
                        new
                        {
                            Id = 3,
                            Name = " PetCategory 2"
                        },
                        new
                        {
                            Id = 4,
                            Name = " PetCategory 3"
                        },
                        new
                        {
                            Id = 5,
                            Name = " PetCategory 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
